### ISSUE TITLE
Build error !!

### ISSUE THREAD

**Issue by qboticslabs** [cubei/FlappyCow#18]
![image](https://cloud.githubusercontent.com/assets/10907702/18356267/af6ce06e-7609-11e6-86d9-0f47fe0b0029.png)

Getting this error while building this project in android studio 2.1.3 !!

**Comment by cubei** [comment]
Have you done everything according to the instruction?

https://github.com/cubei/FlappyCow/blob/master/INSTRUCTIONS.md

**Comment by qboticslabs** [comment]
yes, now i just did some patches and building now.. Can you please compile this package in latest android studio and update the instructions. I think there are lot of changes happening in android studio and libraries so updating instruction will be useful for developers !!

**Comment by cubei** [comment]
I haven't done any android app development in a while. If you found the error, feel free to create a pull request.

**Comment by cubei** [comment]
I have now pushed the repo as Android Studio project.
